apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rvde
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rvde
    app.kubernetes.io/part-of: byoc-app-koar
  name: rvdeeixp
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: rvde
    weight: null
status: {}
