apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rvde
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rvde
    app.kubernetes.io/part-of: byoc-app-koar
  name: rvde
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: rvde
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: rvde
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ukwq-tenant/byoc-app-koar/rvde@sha256:f30e3e6369327927233f980bcdca7536e7e43b6f5e94c161b620b5fc0ac08a6d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
