apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rvde
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rvde
    app.kubernetes.io/part-of: byoc-app-koar
  name: rvde
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: rvde
status:
  loadBalancer: {}
